name: simple_api_service
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/your_username/simple_api_service
repository: https://github.com/your_username/simple_api_service
issue_tracker: https://github.com/your_username/simple_api_service/issues

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  dio: ^5.9.0
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
