name: simple_api_service
description: A robust Dart package for managing API calls with a built-in request queue, unified responses, and flexible error handling.
version: 0.0.1
homepage: https://github.com/devesh12335/simple_api_service
repository: https://github.com/devesh12335/simple_api_service
issue_tracker: https://github.com/devesh12335/simple_api_service/issues

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  dio: ^5.9.0
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
